---
title: "ConsumerComplaintDatabase"
author: "mspcvsp"
date: "04/04/2015"
output: html_document
---

```{r downloadData}
library(caret)
library(choroplethr)
library(choroplethrMaps)
library(data.table)
library(ggplot2)
library(RColorBrewer)
library(ggmap)

data(state.regions)

source("./dataCleaning.R")
source("./dataAnalysis.R")
set.seed(58978160)

# Download data if directory doesn't exist
if (is.na(file.info("./Data")[1,"isdir"])) {
    dir.create("./Data")

    # Initialize the CFPB Consumer Complaint Database URL
    fileURL <- paste0('https://data.consumerfinance.gov/api/views',
                      '/x94z-ydhh/rows.csv?accessType=DOWNLOAD')
    
    download.file(fileURL, destfile="./Data/rows.csv", method="curl")
}  

analyticDataPath <- "./AnalyticData"

# Generate training, validation, & testing data if it doesn't exist
if (is.na(file.info(file.path(analyticDataPath,
                              "/trainingData.csv"))[1,"size"])) {
    cleanData <- loadComplaintData(csvFilePath="./Data/rows.csv",
                                   maximumPercentMissing=10.0)

    complaintData <- cleanData$complaintData
    percentMissingData <- cleanData$percentMissingData
    rm(cleanData)

    save(file=file.path(analyticDataPath, "PercentMissingData.RData"),
         percentMissingData)

    splitData(analyticDataPath,
              complaintData)
}

load(file=file.path(analyticDataPath, "PercentMissingData.RData"))

trainingData <- read.csv(file.path(analyticDataPath,
                                   "trainingData.csv"),
                         header=TRUE)

trainingData$companyid <- as.factor(as.character(trainingData$companyid))
```

```{r mortgagePercentage}
summaryIssueCategoryPercentage <- table(trainingData$issuecategory)

summaryIssueCategoryPercentage <-
    sort(100 * summaryIssueCategoryPercentage / 
         sum(summaryIssueCategoryPercentage), decreasing=TRUE)

stateIssueCategoryPercentage <-
    computeStateIssueCategoryPercentage(trainingData)

mortgagePercentage <- initializePercentIssue("mortgage",
                                             stateIssueCategoryPercentage,
                                             state.regions)

# http://cran.r-project.org/web/packages/choroplethr/vignettes/
#   b-state-choropleth.html
choro = StateChoropleth$new(mortgagePercentage)
choro$title <- "Percentage of Mortgage Complaints"
choro$ggplot_scale = scale_fill_brewer(palette="PuBuGn")
choro$render()
ggsave("./PercentageOfMortgageComplaints.png")
```

```{r debtCollectionPercentage}
debtCollectionPercentage <-
    initializePercentIssue("debtcollection",
                           stateIssueCategoryPercentage,
                           state.regions)

choro = StateChoropleth$new(debtCollectionPercentage)
choro$title <- "Percentage of Debt Collection Complaints"
choro$ggplot_scale = scale_fill_brewer(palette="YlGnBu")
choro$render()
```

```{r creditPercentage}
creditPercentage <- initializePercentIssue("credit",
                                           stateIssueCategoryPercentage,
                                           state.regions)

choro = StateChoropleth$new(creditPercentage)
choro$title <- "Percentage of Credit Complaints"
choro$ggplot_scale = scale_fill_brewer(palette="Oranges")
choro$render()
```

```{r bankingPercentage}
bankingPercentage <- initializePercentIssue("banking",
                                            stateIssueCategoryPercentage,
                                            state.regions)

choro = StateChoropleth$new(bankingPercentage)
choro$title <- "Percentage of Banking Complaints"
choro$ggplot_scale = scale_fill_brewer(palette="RdPu")
choro$render()
```

```{r vizTopFiveOhioIssueCategories}
if (is.na(file.info(file.path(analyticDataPath,
                              "/ohioMapData.RData"))[1,"size"])) {
    ohioMap <- get_map("ohio",zoom=7,source="stamen",maptype="toner")
    
    topFiveOhioIssueCategories <-
        estimateTopFiveStateIssueCategories(trainingData, "OH")
    
    save(ohioMap,topFiveOhioIssueCategories,
         file=file.path(analyticDataPath,"/ohioMapData.RData"))
}
load(file=file.path(analyticDataPath,"/ohioMapData.RData"))

ggmap(ohioMap) + geom_point(aes(x=lon,
                                y=lat,
                                colour=issuecateogry,
                                size=percentageRange),
                                alpha=0.5,
                                data=topFiveOhioIssueCategories) +
    scale_color_brewer(palette="Dark2") + 
    ggtitle('Estimated Top Five Consumer Complaint Issue Cateogries')
ggsave("./topFiveOhioIssueCategories.png")
```

```{r vizTopFiveTexasIssueCategories}
if (is.na(file.info(file.path(analyticDataPath,
                              "/texasMapData.RData"))[1,"size"])) {
    texasMap <- get_map("texas",zoom=6,source="stamen",maptype="toner")
    
    topFiveTexasIssueCategories <-
        estimateTopFiveStateIssueCategories(trainingData, "TX")
    
    save(texasMap,topFiveTexasIssueCategories,
         file=file.path(analyticDataPath,"/ohioMapData.RData"))
}
load(file=file.path(analyticDataPath,"/texasMapData.RData"))

ggmap(texasMap) + geom_point(aes(x=lon,
                                 y=lat,
                                 colour=issuecateogry,
                                 size=percentageRange),
                                 alpha=0.5,
                                 data=topFiveTexasIssueCategories) +
    scale_color_brewer(palette="Dark2") + 
    ggtitle('Estimated Top Five Consumer Complaint Issue Cateogries')
ggsave("./topFiveTexasIssueCategories.png")
```








```